name: Run .NET 9 Project on Multiple OS

on:
  workflow_dispatch:

jobs:
  # Ubuntu - 3 runs
  ubuntu-run:
    name: Ubuntu Run ${{ matrix.run_number }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        run_number: [1, 2, 3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run Project (Ubuntu ${{ matrix.run_number }})
        run: dotnet run --configuration Release --arch x64

  # Windows - 3 runs
  windows-run:
    name: Windows Run ${{ matrix.run_number }}
    runs-on: windows-latest
    strategy:
      matrix:
        run_number: [1, 2, 3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run Project (Windows ${{ matrix.run_number }})
        run: dotnet run --configuration Release --arch x64

  # macOS - 3 runs
  macos-run:
    name: macOS Run ${{ matrix.run_number }}
    runs-on: macos-latest
    strategy:
      matrix:
        run_number: [1, 2, 3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run Project (macOS ${{ matrix.run_number }})
        run: dotnet run --configuration Release --arch x64
