name: Run .NET 9 Project 5 Times

on:
  workflow_dispatch:  # Allows you to manually trigger this workflow

jobs:
  test-dotnet-consistency:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        run_number: [1, 2, 3, 4, 5]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run .NET Project - Run ${{ matrix.run_number }}
        run: dotnet run --configuration Release --arch x64
